Repository aws-controllers-k8s/lambda-controller, pull requests merged in 2022-09, with the labels that each got.

#50 Release artifacts for release v0.1.0
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/templates/deployment.yaml
  helm/values.yaml
Labels: approved

#45 remove dev preview from olm file in preparation for GA
  olm/olmconfig.yaml
Labels: approved, lgtm, needs-ok-to-test

#53 Support `Function` references in `Alias` resource
  apis/v1alpha1/alias.go
  apis/v1alpha1/generator.yaml
  config/crd/bases/lambda.services.k8s.aws_aliases.yaml
  generator.yaml
  helm/crds/lambda.services.k8s.aws_aliases.yaml
  pkg/resource/alias/delta.go
  pkg/resource/alias/references.go
  test/e2e/resources/alias-ref.yaml
  test/e2e/tests/test_alias.py
Labels: approved, lgtm

#54 Support `Function` references in `FunctionUrlConfig` resource
  apis/v1alpha1/function_url_config.go
  apis/v1alpha1/generator.yaml
  config/crd/bases/lambda.services.k8s.aws_functionurlconfigs.yaml
  generator.yaml
  helm/crds/lambda.services.k8s.aws_functionurlconfigs.yaml
  pkg/resource/function_url_config/delta.go
  pkg/resource/function_url_config/references.go
  test/e2e/resources/function_url_config_ref.yaml
  test/e2e/tests/test_function_url_config.py
Labels: approved, lgtm

#55 Initialise `spec.Code` before setting the imageURI
  pkg/resource/function/sdk.go
  templates/hooks/function/sdk_read_one_post_set_output.go.tpl
Labels: approved, lgtm

#56 Fix the `zz_generated.deepcopy` file
  apis/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm

#57 Support `function` reference in `EventSourceMappingSQS` resource
  apis/v1alpha1/event_source_mapping.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/lambda.services.k8s.aws_eventsourcemappings.yaml
  generator.yaml
  helm/crds/lambda.services.k8s.aws_eventsourcemappings.yaml
  pkg/resource/event_source_mapping/delta.go
  pkg/resource/event_source_mapping/references.go
  test/e2e/resources/event_source_mapping_sqs_ref.yaml
  test/e2e/tests/test_event_source_mapping.py
Labels: approved, lgtm
