Repository aws-controllers-k8s/lambda-controller, pull requests merged in 2022-08, with the labels that each got.

#38 Refactor controller end-to-end tests
  test/e2e/bootstrap_resources.py
  test/e2e/conftest.py
  test/e2e/requirements.txt
  test/e2e/service_bootstrap.py
  test/e2e/service_cleanup.py
  test/e2e/tests/helper.py
  test/e2e/tests/test_alias.py
  test/e2e/tests/test_code_signing_config.py
  test/e2e/tests/test_event_source_mapping.py
  test/e2e/tests/test_function.py
Labels: approved, lgtm

#37 Regenerate controller with codegen `v0.19.3`
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  cmd/controller/main.go
  config/controller/deployment.yaml
  generator.yaml
  go.mod
  go.sum
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/values.schema.json
  helm/values.yaml
  pkg/resource/alias/manager.go
  pkg/resource/alias/sdk.go
  pkg/resource/code_signing_config/manager.go
  pkg/resource/code_signing_config/sdk.go
  pkg/resource/event_source_mapping/manager.go
  pkg/resource/event_source_mapping/sdk.go
  pkg/resource/function/manager.go
  pkg/resource/function/sdk.go
  pkg/resource/function/tags.go
  test/e2e/tests/test_alias.py
  test/e2e/tests/test_function.py
Labels: approved, lgtm

#40 Add ECR and S3 ReadOnly access to the recommended policy
  config/iam/recommended-inline-policy
  config/iam/recommended-policy-arn
Labels: approved, lgtm

#41 Stop defaulting non-modified fields when trying to update a Function
  pkg/resource/function/hooks.go
  test/e2e/tests/test_function.py
Labels: approved, lgtm

#39 Bump `aws-sdk-go` version to `v1.44.60`
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/enums.go
  apis/v1alpha1/event_source_mapping.go
  apis/v1alpha1/function.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/lambda.services.k8s.aws_eventsourcemappings.yaml
  config/crd/bases/lambda.services.k8s.aws_functions.yaml
  generator.yaml
  go.mod
  go.sum
  helm/crds/lambda.services.k8s.aws_eventsourcemappings.yaml
  helm/crds/lambda.services.k8s.aws_functions.yaml
  pkg/resource/event_source_mapping/delta.go
  pkg/resource/event_source_mapping/hooks.go
  pkg/resource/event_source_mapping/sdk.go
  pkg/resource/function/delta.go
  pkg/resource/function/sdk.go
  templates/hooks/eventsourcemapping/sdk_update_post_build_request.go.tpl
  templates/hooks/function/sdk_read_one_post_set_output.go.tpl
  test/e2e/tests/test_event_source_mapping.py
  test/e2e/tests/test_function.py
Labels: approved

#43 Keep the desired `code.s3*` fields part of the spec
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/function/sdk.go
  templates/hooks/function/sdk_read_one_post_set_output.go.tpl
  test/e2e/tests/test_function.py
Labels: approved, lgtm

#44 Add `FunctionURLConfig` resource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/function_url_config.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/lambda.services.k8s.aws_functionurlconfigs.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/lambda.services.k8s.aws_functionurlconfigs.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  pkg/resource/function/sdk.go
  pkg/resource/function_url_config/delta.go
  pkg/resource/function_url_config/descriptor.go
  pkg/resource/function_url_config/identifiers.go
  pkg/resource/function_url_config/manager.go
  pkg/resource/function_url_config/manager_factory.go
  pkg/resource/function_url_config/references.go
  pkg/resource/function_url_config/resource.go
  pkg/resource/function_url_config/sdk.go
  test/e2e/resources/function_url_config.yaml
  test/e2e/tests/helper.py
  test/e2e/tests/test_function_url_config.py
Labels: approved, lgtm

#46 Scope the `iam:PassRole` in `recommened-inline-policy` to lambda service
  config/iam/recommended-inline-policy
Labels: approved

#47 Add `docker-ecr-auth` rule to testing Makefile
  test/e2e/resources/lambda_function/Makefile
Labels: approved, lgtm, ok-to-test

#48 Adding `service-team` members in the team controller alias
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test
