Repository aws-controllers-k8s/lambda-controller, pull requests merged in 2023-07, with the labels that each got.

#95 Release artifacts for release v1.1.0
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#96 Update recommended-inline-policy with VPC permissions
  config/iam/recommended-inline-policy
Labels: approved, lgtm, ok-to-test

#99 Release artifact for release `v1.1.1`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#100 Add ability to reference role created by iam-controller
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/function.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/lambda.services.k8s.aws_functions.yaml
  config/rbac/cluster-role-controller.yaml
  generator.yaml
  go.mod
  go.sum
  helm/crds/lambda.services.k8s.aws_functions.yaml
  helm/templates/cluster-role-controller.yaml
  pkg/resource/function/delta.go
  pkg/resource/function/references.go
Labels: approved, lgtm, needs-ok-to-test

#101 Release artifact for release v1.2.0
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm, needs-ok-to-test

#103 Remove terminal condition for InvalidParameterValueException
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/function/sdk.go
  test/e2e/requirements.txt
Labels: approved, lgtm, ok-to-test

#104 Release v1.2.1
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm, ok-to-test

#97 Adding ProvisionedConcurrency Support for Alias
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/alias.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/lambda.services.k8s.aws_aliases.yaml
  documentation.yaml
  generator.yaml
  helm/crds/lambda.services.k8s.aws_aliases.yaml
  pkg/resource/alias/delta.go
  pkg/resource/alias/hooks.go
  pkg/resource/alias/sdk.go
  pkg/resource/function/hooks.go
  templates/hooks/alias/sdk_create_post_set_output.go.tpl
  templates/hooks/alias/sdk_update_pre_build_request.go.tpl
  test/e2e/resources/alias_provisioned_concurrency.yaml
  test/e2e/tests/helper.py
  test/e2e/tests/test_alias.py
Labels: approved, lgtm

#105 Release artifacts for release v1.3.0
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm
